server:
  port: ${SPRING_BACKEND_PORT}
spring:
  datasource:
    postgres:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
    h2:
      url: ${DATABASE_H2_URL}
      username: ${DATABASE_H2_USER}
      password: ${DATABASE_H2_PASSWORD}
      driverClassName: ${DRIVERCLASSNAME_H2}
      console:
        enabled: true
        path: /h2-console
        settings.trace: false
        settings.web-allow-others: false
  jpa:
    database-platform: ${DATABASE_PLATFORM_H2}


